mysite/urls.py
from django.contrib import admin
from django.urls import path, include

import login_app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('portal.urls'))
    # path('', include('login_app.urls')),
]

portal/urls.py
from django.urls import path

from . import views

app_name = 'portal'
urlpatterns = [
    # Homepage
    path('', views.home, name='home'),
    path('logout', views.logout_user, name='logout'),
    # -----------------------------------------------------------------------------------------------------
    #                                           STUDENTS
    # Student Sign-Up
    path('student_sign_up', views.student, name='student_link'),
    # Student Dashboard
    path('student_dashboard', views.student_dashboard, name='student_dashboard'),
    # Class Lookup
    path('class_search', views.student_class_lookup, name='student_class_lookup'),
    # Class Lookup Results
    path('results', views.class_results, name='class_results'),
    # Class Sections
    path('<str:year>/class_view', views.class_view, name='class_view'),
    # Student's Schedule
    path('student_schedule', views.student_schedule, name='student_schedule'),
    # Student's Schedule Conflict Page
    path('student_schedule_warning', views.student_schedule_warning, name='student_schedule_conflict'),
    # Add Class to Shopping Cart
    path('<str:year>/add_class', views.add_class, name='add_class'),
    # Shopping Cart
    path('student_shopping_cart', views.student_shopping_cart, name='student_shopping_cart'),
    # Remove Class
    path('remove_class', views.remove_class, name='remove_class'),
    #Add Class to Schedule
    path('<str:year>/add_to_schedule', views.add_to_schedule, name='add_to_schedule'),
    #Remove Class to Schedule
    path('remove_from_shopping', views.remove_from_shopping, name='remove_from_shopping'),
    #Send Schedule to Advisor
    path('send_schedule', views.send_schedule, name='send_schedule'),

    # -----------------------------------------------------------------------------------------------------

    # -----------------------------------------------------------------------------------------------------
    #                                           Advisors
    # Advisor Sign-Up
    path('advisor_sign_up', views.advisor, name='advisor_link'),
    # Advisor Dashboard
    path('advisor_dashboard', views.advisor_dashboard, name='advisor_dashboard'),
    # Manage Students
    path('manage_students', views.manage_students, name='manage_students'),
    # Student Profile
    path('student_profile', views.student_profile, name='student_profile'),
    # Advisor Schedule View
    path('view_schedule', views.advisor_schedule_view, name='advisor_schedule_view'),
    # Approve Student Schedule
    path('approve_schedule', views.approve_schedule, name='approve_schedule'),
    # Reject Student Schedule
    path('reject_schedule', views.reject_schedule, name='reject_schedule'),
    # -----------------------------------------------------------------------------------------------------
]

portal/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from portal import departments


class Advisor(models.Model):
    # advisor_id = models.IntegerField(primary_key=True)
    advisor_first_name = models.CharField(max_length=255)
    advisor_last_name = models.CharField(max_length=255)
    advisor_email = models.EmailField(max_length=255)
    DEPARTMENT_CHOICES = departments.DEPARTMENTS
    advisor_department = models.CharField(
        max_length=50,
        choices=DEPARTMENT_CHOICES,
        default='',
    )

    def __str__(self):
        return self.advisor_email


class Student(models.Model):
    student_first_name = models.CharField(max_length=255)
    student_last_name = models.CharField(max_length=255)
    student_email = models.EmailField(max_length=255)
    advisor = models.ForeignKey(Advisor, on_delete=models.CASCADE, default="5")
    FIRST_YEAR = '1'
    SECOND_YEAR = '2'
    THIRD_YEAR = '3'
    FOURTH_YEAR = '4'
    YEAR_IN_SCHOOL_CHOICES = [
        (FIRST_YEAR, '1'),
        (SECOND_YEAR, '2'),
        (THIRD_YEAR, '3'),
        (FOURTH_YEAR, '4'),
    ]
    year_in_school = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default='',
    )
    schedule = models.ForeignKey('Schedule', on_delete=models.CASCADE, blank=True, null=True, default='')
    shopping_cart = models.ForeignKey('ShoppingCart', on_delete=models.CASCADE, blank=True, null=True, default='')
    def __str__(self):
        return self.student_email


class Department(models.Model):
    subject = models.CharField(max_length=255)
    descr = models.CharField(max_length=255)

    def __str__(self):
        return self.descr


class Class(models.Model):
    subject = models.CharField(max_length=255)
    subject_descr = models.CharField(max_length=255)
    catalog_nbr = models.CharField(max_length=255)
    descr = models.CharField(max_length=255)

    def __str__(self):
        return self.subject + '-' + self.catalog_nbr


class ClassSection(models.Model):
    class_nbr = models.CharField(max_length=255)
    class_section = models.CharField(max_length=255)
    class_capacity = models.CharField(max_length=255)
    enrollment_total = models.CharField(max_length=255)
    enrollment_available = models.CharField(max_length=255)
    units = models.CharField(max_length=255)
    days = models.CharField(max_length=255)
    start_time = models.CharField(max_length=255)
    end_time = models.CharField(max_length=255)
    instructor = models.CharField(max_length=255)
    facility_descr = models.CharField(max_length=255)
    catalog_nbr = models.CharField(max_length=255, default='')
    season = models.CharField(max_length=255)
    # new fields
    subject = models.CharField(max_length=255, null=True)
    subject_descr = models.CharField(max_length=255, null=True)
    descr = models.CharField(max_length=255, null=True)
    section_type = models.CharField(max_length=255, null=True)


class Schedule(models.Model):
    season = models.CharField(max_length=255)
    classes = ArrayField(
        models.CharField(max_length=255),
        blank=True,
        null=True,
    )
    is_approved = models.BooleanField()
    is_viewed = models.BooleanField()
    is_sent = models.BooleanField()
    def credit_count(self):
        creditCount = 0
        for c in self.classes:
            curClass = ClassSection.objects.get(pk=c)
            creditCount += int(curClass.units[0])
        return creditCount


class ShoppingCart(models.Model):
    season = models.CharField(max_length=255)
    classes = ArrayField(
        models.CharField(max_length=255),
        blank=True,
        null=True,
    )

portal/forms.py
from django import forms
from .models import Student, Advisor


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        exclude = ['student_email']


class AdvisorForm(forms.ModelForm):
    class Meta:
        model = Advisor
        fields = '__all__'

portal/views.py
import datetime
import json
import requests
from django.contrib import messages
from django.contrib.auth import logout
from django.core import serializers
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from requests.exceptions import HTTPError
from .models import *


def home(request):
    # from https://stackoverflow.com/questions/14639106/how-can-i-retrieve-a-list-of-field-for-all-objects-in-django
    uva_students = list(Student.objects.all().values_list('student_email', flat=True))
    uva_advisors = list(Advisor.objects.all().values_list('advisor_email', flat=True))
    if request.user.is_authenticated and request.user.email in uva_students:
        return HttpResponseRedirect(reverse('portal:student_dashboard'))
    if request.user.is_authenticated and request.user.email in uva_advisors:
        return HttpResponseRedirect(reverse('portal:advisor_dashboard'))
    return render(request, 'pages/home.html', {"students": uva_students, "advisors": uva_advisors})

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('portal:home'))

def student(request):
    uva_students = list(Student.objects.all().values_list('student_email', flat=True))
    if request.user.is_authenticated and request.user.email in uva_students:
        return HttpResponseRedirect(reverse('portal:student_dashboard'))
    if request.method == "POST":
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        year = request.POST['year']
        newStudent = Student(
            student_first_name=first_name,
            student_last_name=last_name,
            student_email=email,
            year_in_school=year
        )
        newStudent.save()
        return HttpResponseRedirect(reverse('portal:student_dashboard'))
    return render(request, "pages/student_sign_up.html")

def student_dashboard(request):
    student_logged_in = Student.objects.get(student_email=request.user.email)
    return render(request, 'pages/student_dashboard.html', {"student": student_logged_in})

def get_departments():
    all_departments = Department.objects.all()
    return all_departments

def student_class_lookup(request):
    student_logged_in = Student.objects.get(student_email=request.user.email)
    try:
        all_departments = get_departments()
        return render(request, 'pages/student_class_lookup.html', {"student": student_logged_in, "departments": all_departments, "error": ""})
    # from https://pynative.com/parse-json-response-using-python-requests-library/
    except HTTPError as http_err:
        print(f'HTTP error occurred: {http_err}')
    return render(request, 'pages/student_class_lookup.html', {"student": student_logged_in, "error": ""})

def class_results(request):
    test_student = Student.objects.get(student_email=request.user.email)
    class_nbr = request.POST['course_num']
    if class_nbr != "":
        classes = Class.objects.filter(subject=request.POST['department']).filter(catalog_nbr=class_nbr)
    else:
        classes = Class.objects.filter(subject=request.POST['department']).order_by('catalog_nbr')
    return render(request, 'pages/class_results.html',
                  {"classes": classes, "student": test_student, "year": request.POST['year']})

def class_view(request, year):
    c = Class.objects.get(pk=request.POST['ClassPK'])
    baseURL = 'https://sisuva.admin.virginia.edu/psc/ihprd/UVSS/SA/s/WEBLIB_HCX_CM.H_CLASS_SEARCH.FieldFormula.IScript_ClassSearch?institution=UVA01'
    url = baseURL + "&subject=" + c.subject + "&catalog_nbr=" + c.catalog_nbr + "&term=123" + year
    r = requests.get(url)
    classData = r.json()
    # logic here to fix times to be able to see in class view page - json will have long times like 15.30.00.00000
    for d in classData:
        for m in d['meetings']:
            if m['start_time'] != '':
                st_time = m['start_time'][0:5]
                en_time = m['end_time'][0:5]
                time_format = '%H.%M'  # The format
                st_time_str = datetime.datetime.strptime(st_time, time_format)
                st_time_str_2 = st_time_str.strftime("%I.%M %p")
                st_time_str_2 = st_time_str_2.replace(".", ":")
                en_time_str = datetime.datetime.strptime(en_time, time_format)
                en_time_str_2 = en_time_str.strftime("%I.%M %p")
                en_time_str_2 = en_time_str_2.replace(".", ":")
                m['start_time'] = st_time_str_2
                m['end_time'] = en_time_str_2
    return render(request, 'pages/class_view.html', {"classData": classData, "class": c.subject + '-' + c.descr, "year": year})

def student_schedule(request):
    student_logged_in = Student.objects.get(student_email=request.user.email)
    schedule = []
    print(student_logged_in.schedule)
    if student_logged_in.schedule is None or len(student_logged_in.schedule.classes) == 0:
        return render(request, 'pages/student_schedule.html', {"schedule": "empty"})
    else:
        for item in student_logged_in.schedule.classes:
            curClass = ClassSection.objects.get(pk=item)
            schedule.append(curClass)
        schedule = serializers.serialize('json', schedule)
        data = json.loads(schedule)
        for d in data:
            if d['fields']['start_time'] != '':
                st_time = d['fields']['start_time'][0:5]
                en_time = d['fields']['end_time'][0:5]
                time_format = '%H.%M'  # The format
                st_time_str = datetime.datetime.strptime(st_time, time_format)
                st_time_str_2 = st_time_str.strftime("%I.%M %p")
                st_time_str_2 = st_time_str_2.replace(".", ":")
                en_time_str = datetime.datetime.strptime(en_time, time_format)
                en_time_str_2 = en_time_str.strftime("%I.%M %p")
                en_time_str_2 = en_time_str_2.replace(".", ":")
                d['fields']['start_time'] = st_time_str_2
                d['fields']['end_time'] = en_time_str_2
        return render(request, 'pages/student_schedule.html',
                      {"schedule": data, "is_approved": student_logged_in.schedule.is_approved,
                       "is_viewed": student_logged_in.schedule.is_viewed,
                       "is_sent": student_logged_in.schedule.is_sent})

def student_schedule_warning(request):
    student_logged_in = Student.objects.get(student_email=request.user.email)
    schedule = []
    print(student_logged_in.schedule)
    # this if statement shouldn't be necessary...since no conflict will arise if schedule is empty
    if len(student_logged_in.schedule.classes) == 0:
        return render(request, 'pages/student_schedule.html', {"schedule": "empty"})
    else:
        for item in student_logged_in.schedule.classes:
            curClass = ClassSection.objects.get(pk=item)
            schedule.append(curClass)
        schedule = serializers.serialize('json', schedule)
        data = json.loads(schedule)
        for d in data:
            if d['fields']['start_time'] != '':
                st_time = d['fields']['start_time'][0:5]
                en_time = d['fields']['end_time'][0:5]
                time_format = '%H.%M'  # The format
                st_time_str = datetime.datetime.strptime(st_time, time_format)
                st_time_str_2 = st_time_str.strftime("%I.%M %p")
                st_time_str_2 = st_time_str_2.replace(".", ":")
                en_time_str = datetime.datetime.strptime(en_time, time_format)
                en_time_str_2 = en_time_str.strftime("%I.%M %p")
                en_time_str_2 = en_time_str_2.replace(".", ":")
                d['fields']['start_time'] = st_time_str_2
                d['fields']['end_time'] = en_time_str_2
        return render(request, 'pages/student_schedule_conflict.html', {"schedule": data})

def advisor(request):
    uva_advisors = list(Advisor.objects.all().values_list('advisor_email', flat=True))
    if request.user.is_authenticated and request.user.email in uva_advisors:
        return HttpResponseRedirect(reverse('portal:advisor_dashboard'))
    if request.method == "POST":
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        department = request.POST['department']
        newAdvisor = Advisor(
            advisor_first_name=first_name,
            advisor_last_name=last_name,
            advisor_email=email,
            advisor_department=department
        )
        newAdvisor.save()
        return HttpResponseRedirect(reverse('portal:advisor_dashboard'))
    return render(request, "pages/advisor_sign_up.html")

def advisor_dashboard(request):
    advisor_logged_in = Advisor.objects.get(advisor_email=request.user.email)
    return render(request, 'pages/advisor_dashboard.html', {"advisor": advisor_logged_in})

def checkForConflicts(student_user, meetings):
    schedule = []
    if student_user.schedule is None:
        return False
    for item in student_user.schedule.classes:
        curClass = ClassSection.objects.get(pk=item)
        schedule.append(curClass)
    schedule = serializers.serialize('json', schedule)
    data = json.loads(schedule)
    # in case where there is no class in schedule, automatically, no conflict
    if not data:
        return False
    else:
        for c in data:
            if c['fields']['days'] == meetings['days']:
                if c['fields']['start_time'] <= meetings['start_time'] <= c['fields']['end_time']:
                    return True
                elif c['fields']['start_time'] <= meetings['end_time'] <= c['fields']['end_time']:
                    return True
        return False


def add_to_schedule(request, year):
    class_nbr = (request.POST['class_number'])

portal/templates/pages/advisor_schedule_view.html
{% load socialaccount %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<link rel="stylesheet" href="{% static 'portal/style.css' %}">
<html lang="en">
  <!-- Style here for navbar taken from https://www.w3schools.com/howto/howto_js_topnav.asp -->

<head>
    <meta charset="UTF-8">
    <title>View Schedule</title>
</head>

<body>
<!-- NAVIGATION -->
<div class="topnav">
    <a href="{% url 'portal:advisor_dashboard' %}">Dashboard</a>
    <a href="{% url 'portal:manage_students' %}">Manage Students</a>
    <div class="topnav-right">
      <a href="{% url 'portal:logout' %}">Log Out</a>
    </div>
</div>

<!-- CONTENT -->
<div class="container-flex">
  <div class="border2">
    <h2>{{advisee.student_first_name}} {{advisee.student_last_name}}'s Schedule:</h2>
    {% for class in schedule %}
    <h5> {{class.fields.subject}}: {{class.fields.catalog_nbr}} - {{class.fields.class_section}} - {{class.fields.section_type}}</h5>
    <h6>&emsp; Enrollment: {{class.fields.enrollment_total}} / {{class.fields.class_capacity}}</h6>
        <h6>&emsp; Time: {{class.fields.start_time}} - {{class.fields.end_time}}</h6>
        <h6>&emsp; Days: {{class.fields.days}} </h6>
        <h6>&emsp; Room: {{class.fields.facility_descr}}</h6>
        <h6>&emsp; Instructor: {{class.fields.instructor}}</h6>
    {% endfor %}
    <br></br>
    <div class="btn-group" role="group">
        <form action="{% url 'portal:student_profile' %}" method="post">
          {% csrf_token %}
            <button type="submit" class="btn btn-outline-dark btn-rounded" name="advisee_email" value={{advisee.student_email}}>Return to Student's Profile</button>
        </form>
        {% if is_sent %}
            {% if is_viewed %}
                {% if is_approved %}
                    <div class="border2">
                        <h6> Schedule Has Been Approved</h6>
                    </div>
                {% else %}
                    <div class="border2">
                        <h6> Schedule Has Been Rejected</h6>
                    </div>
                {% endif %}
            {% else %}
                <form action="{% url 'portal:approve_schedule' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-dark btn-secondary" name="approve_schedule" value={{advisee.student_email}}>Approve Schedule</button>
                </form>
                <form action="{% url 'portal:reject_schedule' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-dark btn-secondary" name="approve_schedule" value={{advisee.student_email}}>Reject Schedule</button>
                </form>
            {% endif %}
        {% else %}
            <div class="border2">
                <h6> Student has not requested approval</h6>
            </div>
        {% endif %}
    </div>
    <!-- Abby note: the button links don't work -->
    <!-- Abby note: the dark button colors are wrong on the advisor end -->
  </div>
</div>
<!-- 
    <form action="{% url 'portal:student_profile' %}" method="post">
        {% csrf_token %}
        <button name="advisee_email" value={{advisee.student_email}}>return to student's profile</button><br>
    </form>
  <div class="header">
    <h2>{{advisee.student_first_name}} {{advisee.student_last_name}}'s Schedule:</h2>
    </div>
    {% for class in schedule %}
      <div class="borders">
        <h2> {{class.fields.subject}}: {{class.fields.catalog_nbr}} - {{class.fields.class_section}} - {{class.fields.section_type}}</h2>
        <h4>&emsp; Enrollment: {{class.fields.enrollment_total}} / {{class.fields.class_capacity}}</h4>
            <h4>&emsp; Time: {{class.fields.start_time}} - {{class.fields.end_time}}</h4>
            <h4>&emsp; Days: {{class.fields.days}} </h4>
            <h4>&emsp; Room: {{class.fields.facility_descr}}</h4>
            <h4>&emsp; Instructor: {{class.fields.instructor}}</h4>
      </div>
    {% endfor %}
  <button name="approve_schedule" value={{advisee.student_email}}>Approve Schedule</button><br> -->
  <!-- <button class="btn btn-outline-dark btn-rounded" name="advisee_email" value={{advisee.student_email}}>Return to Student's Profile</button><br>
    <button class="btn btn-dark" name="approve_schedule" value={{advisee.student_email}}>Approve Schedule</button><br> -->
</body>

<footer class="bg-white text-center text-lg-start">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase"></h5>
        <p></p>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase"></h5>
        <p></p>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3 text-light" style="background-color: #232D4B;">
    © 2023 Copyright: Abby Dhakal, Gavin Fortner, Ananya Ananda, Ashwin Shankar, Caleb Lee
  </div>
  <!-- Copyright -->
</footer>
</html>

portal/templates/pages/student_schedule.html
{% load socialaccount %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link rel="stylesheet" href="{% static 'portal/style.css' %}">
<html lang="en">
  <!-- Style here for navbar taken from https://www.w3schools.com/howto/howto_js_topnav.asp -->
<head>
    <meta charset="UTF-8">
    <title>Schedule</title>
</head>

  <body>
     <!--{% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}-->
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message | safe }}
        </div>
    {% endfor %}

<!-- NAVIGATION -->
<div class="topnav">
  <a href="{% url 'portal:student_dashboard' %}">Dashboard</a>
  <a href="{% url 'portal:student_class_lookup' %}">Find Classes</a>
  <a href="{% url 'portal:student_shopping_cart' %}">Shopping Cart</a>
  <a href="{% url 'portal:student_schedule' %}">Schedule</a>
  <div class="topnav-right">
    <a href="{% url 'portal:logout' %}">Log Out</a>
  </div>
</div>

<!-- CONTENT -->
<div class="container-fluid">
  <div class="border2">
    <h2>Schedule</h2>
  
  {% if schedule != "empty" %}
      {% for class in schedule %}
          <form action="{% url 'portal:remove_class' %}" method="post">
              {% csrf_token %}
              <h5> {{class.fields.subject}}: {{class.fields.catalog_nbr}} - {{class.fields.descr}} </h5>
              <h6>&emsp; Enrollment: {{class.fields.enrollment_total}} / {{class.fields.class_capacity}}</h6>
              <h6>&emsp; Time: {{class.fields.start_time}} - {{class.fields.end_time}}</h6>
              <h6>&emsp; Days: {{class.fields.days}} </h6>
              <h6>&emsp; Room: {{class.fields.facility_descr}}</h6>
              <h6>&emsp; Instructor: {{class.fields.instructor}}</h6>
              <button class="btn btn-outline-dark btn-rounded" value="{{class.pk}}"  name>Remove Class</button>
          </form>
      {% endfor %}
          {% if is_sent %}
              {% if is_viewed %}
                    {% if is_approved %}
                        <h5>Schedule has been approved! If you add or remove classes, you will need to request approval again.</h5>
                    {% else %}
                        <h5>Schedule has been rejected. Please change your schedule and send again!</h5>
                    {% endif %}
              {% else %}
                <h5> Schedule has been sent, but is awaiting advisor approval.</h5>
              {% endif %}
          {% else %}
              <form action="{% url 'portal:send_schedule' %}" method="post">
                  {% csrf_token %}
                <button type="submit" class="btn btn-dark" onclick="send_student_Schedule()" class="btn btn-dark">Send Schedule </button>
              </form>
          {% endif %}
      {% else %}
      <h5>No classes added yet.</h5>
  {% endif %}

  <script>
      function send_student_Schedule() {
        alert("Your schedule was just sent! If you change your schedule before your advisor looks at it, you will have to send it again!");
      }
  </script>
  </div>
</div>  
</body>

<footer class="bg-white text-center text-lg-start">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase"></h5>
        <p></p>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase"></h5>
        <p></p>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3 text-light" style="background-color: #232D4B;">
    © 2023 Copyright: Abby Dhakal, Gavin Fortner, Ananya Ananda, Ashwin Shankar, Caleb Lee
  </div>
  <!-- Copyright -->
</footer>
</html>

portal/templates/pages/student_shopping_cart.html
{% load socialaccount %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link rel="stylesheet" href="{% static 'portal/style.css' %}">
<html lang="en">
  <!-- Style here for navbar taken from https://www.w3schools.com/howto/howto_js_topnav.asp -->
  
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
</head>
  <body>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message | safe }}
        </div>
    {% endfor %}

  <!-- NAVIGATION -->
  <div class="topnav">
    <a href="{% url 'portal:student_dashboard' %}">Dashboard</a>
    <a href="{% url 'portal:student_class_lookup' %}">Find Classes</a>
    <a href="{% url 'portal:student_schedule' %}">Schedule</a>
    <a href="{% url 'portal:student_shopping_cart'%}">Shopping Cart</a>
    <div class="topnav-right">
        <a href="{% url 'portal:logout' %}">Log Out</a>
    </div>
  </div>
    <!-- CONTENT -->
    <div>
      <h2>Shopping Cart:</h2>
    </div>
    {% if shopping_cart != "empty" %}
        <div class="info">
        {% for class in shopping_cart %}
                <h2> {{class.fields.subject}}: {{class.fields.catalog_nbr}} - {{class.fields.descr}} </h2>
                <h4>&emsp; Enrollment: {{class.fields.enrollment_total}} / {{class.fields.class_capacity}}</h4>
                <h4>&emsp; Time: {{class.fields.start_time}} - {{class.fields.end_time}}</h4>
                <h4>&emsp; Days: {{class.fields.days}} </h4>
                <h4>&emsp; Room: {{class.fields.facility_descr}}</h4>
                <h4>&emsp; Instructor: {{class.fields.instructor}}</h4>
            <form action="{% url 'portal:add_to_schedule' class.fields.season%}" method="post">
              {% csrf_token %}
                <button name="class_number" value="{{class.fields.class_nbr}}" name>Add to Schedule</button>
            </form>
            <form action="{% url 'portal:remove_from_shopping' %}" method="post">
                {% csrf_token %}
                <button name="class_pk" value="{{class.pk}}" name>Remove Class</button>
            </form>
        {% endfor %}
        </div>
    {% else %}
        <h4>No classes added yet.</h4>
    {% endif %}
  </body>
</html>